name: Continuous Integration

on: 
  push: 
    branches: [ prod, main ]
  pull_request:
    branches: [ prod, main ]

jobs:
  build:
    strategy:
      matrix:
        ubuntu-version: [ ubuntu-22.04 ]
        node-version: [ 22.x, 24.x ]
    runs-on: ${{ matrix.ubuntu-version }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Get latest model version
      id: get-latest-model-version
      shell: bash
      env:
        model_uri: https://tickettagger.blob.core.windows.net/models/model.bin
      # echo "::set-output name=version::$(curl --head '${{ env.model_uri }}' --silent | grep -oP 'ETag: \K0x[0-9A-Fa-f]+')"
      run: |
        echo "version=$(curl --head '${{ env.model_uri }}' --silent | grep -oP 'ETag: \K0x[0-9A-Fa-f]+')" >> $GITHUB_OUTPUT
        
    - name: Cache model
      uses: actions/cache@v3
      id: cache-model
      with:
        path: ~/.tickettagger/models
        key: model-${{ steps.get-latest-model-version.outputs.version }}
        restore-keys: |
          model-
          
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Cache node_modules
      uses: actions/cache@v3
      id: cache-node_modules
      with:
        path: node_modules
        key: node_modules-${{ matrix.ubuntu-version }}-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node_modules-${{ matrix.ubuntu-version }}-${{ matrix.node-version }}-
          node_modules-${{ matrix.ubuntu-version }}-
          node_modules-
          
    - name: Install
      if: steps.cache-node_modules.outputs.cache-hit != 'true'
      run: npm ci

    - name: Start services
      run: docker compose up --wait
      
    - name: Test
      env:
        MONGO_URI: ${{ secrets.MONGO_URI || format('mongodb://{0}:{1}@localhost:27017/ticket-tagger?authSource=admin', 'username', 'password') }}
      run: npm test

    - name: Stop services
      if: always()
      run: docker compose down -v

  image:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-v${{ github.run_id }}
